### PR TITLE
WWW/Newsroom, Homepage Story Automation

### PR DESCRIPTION
**Pull request by cbryant24**
Story: https://trello.com/c/fKbgQfMo

### CODE REVIEW

**Comment by cbryant24** [comment]
@corejh whoops good catch didn't notice that. Should be fixed now.

**Comment by mandythomas** [comment]
@cbryant24 why are you creating a new folder named Manage Site. I think the homepage formats should go in cascade-assets\.cascade-code\Chapman.edu\_cascade\formats\home\ in github. do you agree?  I've also always wanted to move the actual formats in Cascade (that are all related to the Homepage) into a home or homepage subfolder too. Could you do that so we are doing some much needed cleanup and reorganization as we go? Can you ask @corejh if that can be part of this (if not much more effort)

**Comment by cbryant24** [comment]
@mandythomas I wanted to include that file, but I didn't know that `cascade-assets.cascade-code\Chapman.edu_cascade\formats\home\` referred to homepage formats. I like that idea of creating  a subfolder called homepage. @corejh Are you good with that creating a subfolder for the homepage? @mandythomas  were you thinking `cascade-assets.cascade-code\Chapman.edu\_cascade\homepage`

**Comment by corejh** [comment]
@mandythomas @cbryant24 what exactly would we be moving into this folder? does it make sense, and are there any gains for doing this?

**Pull request merged**
