### PR TITLE
Misc format and block fixes

### PR DESCRIPTION
**Pull request by mandythomas**
Misc:
For the the OG And Canonical Tags format, I'm fixing an issue with duplicates of the meta tags (I think the previous Developer tried to group the meta tags together with the new ones for twitter but left them in 2 places in the file, plus removed the fully-qualified domain which we need so adding back.

Fix to remove Panther from Panther Alert heading in the homepage alert.

Small update to 2 links in Law's global nav  menu

Updates to depts in dropdown for Faculty Widget in the 2 and 3 Column Data Definitions.

style for table captions.

### CODE REVIEW

**Comment by mandythomas** [comment]
@corejh this is not related to that Trello card. I did not update the templates which where the meta tag mentioned in that card reside. I updated a different set of meta tags that are in one of the velocity formats

**Comment by mandythomas** [comment]
@corejh and @cbryant24 I still have pending template changes on Dev-Cascade (swapping out the PRIMARY CONTENT region for DEFAULT). So if Chris is doing that other template change soon we'd need to coordinate or wait til I move my template changes to Prod. I wouldn't want him to simply copy the template from Dev to Prod as is right now. i just haven't got around to finishing that project

**Comment by cbryant24** [comment]
@mandythomas I was probably going to make those changes tomorrow most likely but I can hold off to another day on those if you need more time

**Comment by mandythomas** [comment]
@cbryant24 the meta tag change for the template that you're going to do is (I think) to simply remove the chrome=1 in the 2 and 3 Col modular templates. If you simply edit those on DEV and then make same edit on PROD that would be fine. Just DO NOT copy the version from DEV to PROD as that will bring over the changes I made for PRIMARY vs DEFAULT region names. also fyi I have not made that change to anything in github yet. My chg to template and configs was only in Dev-Cascade so far

**Pull request merged**
