### PR TITLE
Update vulnerabilities

### LINKED ISSUE #297: Github reporting vulnerabilities in Degrees and Programs packages.
See ` subprojects/degrees-and-programs/source/static/package-lock.json` section of this page:

- https://github.com/chapmanu/cascade-assets/network/dependencies

@sharissis-brei The alert appeared after your latest PR was merged in. Can you update these? For reference, see this recent PR:

- https://github.com/chapmanu/cascade-assets/pull/294

### PR DESCRIPTION
**Pull request by sharissis-brei**
**Trello Story:** https://trello.com/c/KQdeliYn

Fixes #297

---

I reran npm install in Degrees and Programs, which has updated some of the dependancies in package.json. However, I am unfamiliar with Github's process of searching for vulnerable dependancies, so I haven't tested this. If you are able to point me in the right direction with the next steps, that would be great.

### CODE REVIEW

**Comment by kaylaziegler** [comment]
@sharissis-brei Are you able to access this URL? https://github.com/chapmanu/cascade-assets/network/dependencies#30324618

It might show up as a broken link, let me know

**Comment by sharissis-brei** [comment]
I can access the URL, but I wasn't sure how to use this list to check which dependancies are vulnerable. I don't see any error messages or anything. Would you mind giving me a rundown of what I should be addressing here?

**Comment by kaylaziegler** [comment]
@sharissis-brei Ok that's good you can see the link. 

At the top, you should see 3 packages highlighted in yellow, that each say `Known security vulnerability in {version number}` with a dropdown on the version number. That means somewhere in the `package-lock.json` it refers to those 3 packages with those version numbers, which have known security vulnerabilities.

If you click on the dropdown on each version number, it gives you more details on what the vulnerabilities are and the severities. But more importantly, it also tells you which version you should upgrade to in order to get rid of the vulnerabilities. For example, in this screenshot from the `handlebars.js` package vulnerability, you can see it says it recommends you upgrade to minimum version 4.0.0:
screen shot 2018-03-05 at 5 19 48 pm

So whatever version it says in each of those drop-downs for the 3 packages with vulnerabilities, we should try to do.

**Comment by sharissis-brei** [comment]
@kaylaziegler I'm actually not seeing these packages highlighted in yellow, not sure why. You may need to provide me with the warnings you're seeing.

I'm updating package.json to use the latest dependancies of our app generator. I'll be committing that shortly. Hopefully we shouldn't see warnings after that.

**Comment by sharissis-brei** [comment]
@kaylaziegler I rebuilt using the new dependancies, so new CSS and JS have been generated. However, they shouldn't change any styles or functionality. Still, I think we should copy these new versions of the assets over to Dev Cascade and retest to make sure everything's still working as expected. Since this is separated from the cascade-assets build process, may I proceed with moving the new assets to Dev Cascade?

**Comment by kaylaziegler** [comment]
@sharissis-brei Okay got it. Sorry about that. Here is a screenshot of the vulnerabilities we're getting:

screen shot 2018-03-06 at 10 14 46 am

**Comment by sharissis-brei** [comment]
@kaylaziegler That's great news! Thank you for getting me the details on that.

We still need to test the newly built code assets. It sounds like you're ok with me deploying them to Dev Cascade to test. I'll do that and inform you when we've verified that everything is working properly. After that, we should be ready to merge.

**Comment by sharissis-brei** [comment]
@kaylaziegler I wanted to check in to see if you need anything else from me for this PR.

**Comment by kaylaziegler** [comment]
@sharissis-brei Nope, Chris and I both approved it last week. We've been waiting for the go-ahead from you, you said you were still doing testing.

**Comment by sharissis-brei** [comment]
@kaylaziegler I see. We are all set with testing that and this is ready to merge.

**Comment by kaylaziegler** [comment]
@sharissis-brei Does this require you to make any changes to production? So after I merge, are you going to deploy any assets (javascript, css) to cascade at all?

**Comment by sharissis-brei** [comment]
@kaylaziegler The only thing I'd need to do is copy over the Degrees and Programs CSS and JS. No functionality or styles have changed, but the build is different because of the new dependancies, so we'd just be doing it to keep things consistent with what's in Dev Cascade.

I can deploy the assets – shouldn't take more than a couple minutes. Since this is not part of the normal assets build, is it ok for me to proceed with this now?

**Comment by kaylaziegler** [comment]
@sharissis-brei Let me merge it right now and then you can definitely proceed with deploying the assets you need to.

**Comment by sharissis-brei** [comment]
@kaylaziegler Deploy to production is complete.

**Pull request merged**
