### PR TITLE
Resolves tiny font at https://web.chapman.edu/PhoneDirectory/

### PR DESCRIPTION
**Pull request by nicholasnadel**
To test, copy and paste the styles at https://web.chapman.edu/PhoneDirectory/

### CODE REVIEW

**Comment by nicholasnadel** [comment]
> there's a couple of things not resolved by these changes. the search button is getting chopped short for example

not sure what it looked like initially but the following gets close. I have the same concerns that although there are no search results for the id in Cascade-Assets that it might be used in a rogue element somewhere else on the site. Not sure if I'm missing a page-template class or something I can use for /PhoneDirectory/ specificity 

```
input#btnSearch {
    width: 12rem;
    background-position: 8.0rem;
    height: 5rem;
}
```

**Comment by nicholasnadel** [comment]
The page is using a custom.css file

```
/* Menu CSS */
ul# {
    width: 100%;
}

ul#topnav li {
    background: #000;
    position: relative;
    list-style-type: none;
    text-align: left;
    border-bottom: 1px solid #fff;
    border-left: 1px solid #fff;
    line-height: 2em;
}

.ie8 ul#topnav li, ie7 ul#topnav li {
    float: left;
}

ul#topnav li a, ul#topnave li a:visited {
    color: #FFF;
    font-weight: bold;
    padding: 10px;
    border: none;
}

@media only screen and (min-width: 780px) {

    ul#topnav li:hover a, ul#topnav li a:hover {
        background-position: left bottom;
    }

    ul#topnav li {
        float: left;
    }

        ul#topnav li .sub {
            position: absolute;
            top: 16px;
            left: 0;
            z-index: 99999;
            padding: 3px 5px 5px 0px;
            float: left;
            display: none;
            background-color: Black;
        }

            ul#topnav li .sub ul {
                list-style: none;
                margin: 0;
                padding: 0;
                width: 150px;
                float: left;
            }

    ul#topnav .sub ul li {
        margin-left: 10px;
        padding: 5px;
        width: 100%;
        text-align: left;
    }
}

@media only screen and (min-width: 1024px) {
}

@media only screen and (min-width: 1085px) {
}

/* forms */
fieldset {
    border: none;
    margin: 0;
    padding: 0;
}

    fieldset legend {
        display: none;
    }

    fieldset ol {
        padding: 0;
        list-style: none;
    }

        fieldset ol li {
            padding-bottom: 5px;
        }

    fieldset label {
        display: block;
        font-size: 1.2em;
        font-weight: 600;
    }

        fieldset label.checkbox {
            display: inline;
        }

    fieldset input[type="text"], fieldset input[type="password"] {
        border: 1px solid #e2e2e2;
        color: #333;
        font-size: 1.2em;
        margin: 5px 0 6px 0;
        padding: 5px;
        width: 300px;
    }

        fieldset input[type="text"]:focus, fieldset input[type="password"]:focus {
            border: 1px solid #7ac0da;
        }

    fieldset input[type="submit"] {
        background-color: #d3dce0;
        border: 1px solid #787878;
        cursor: pointer;
        font-size: 1.2em;
        font-weight: 600;
        padding: 7px;
    }

/* ajax login/registration dialog */
.modal-popup {
    font-size: 0.7em;
}

    .modal-popup input[type="text"], .modal-popup input[type="password"] {
        width: 90%;
    }

/* info and errors */
.message-info {
    border: 1px solid;
    clear: both;
    padding: 10px 20px;
}

.message-error {
    clear: both;
    color: #e80c4d;
    font-size: 1.1em;
    font-weight: bold;
    margin: 20px 0 10px 0;
}

.message-success {
    color: #7ac0da;
    font-size: 1.3em;
    font-weight: bold;
    margin: 20px 0 10px 0;
}

.error {
    color: #e80c4d;
}

/* styles for validation helpers */
.field-validation-error {
    color: #e80c4d;
    font-weight: bold;
}

.field-validation-valid {
    display: none;
}

input[type="text"].input-validation-error, input[type="password"].input-validation-error {
    border: 1px solid #e80c4d;
}

.validation-summary-errors {
    color: #e80c4d;
    font-weight: bold;
    font-size: 1.1em;
}

.validation-summary-valid {
    display: none;
}

.content-height {
    max-height: 350px;
}

.window {
    padding: 10px 45px 10px 45px;
    background-color: #E5E2CF;
    border-left: 1px solid white;
    border-bottom: 1px solid #A58F75;
}

.ui-window {
    border: 1px solid #D9D8D2;
    border-width: 1px;
    color: #353430;
    margin-bottom: 20px;
    background-color: #FAF8EF;
    -webkit-box-shadow: 0px 0px 7px #434343;
    box-shadow: 0px 0px 7px #434343;
}

.ui-window-titlebar {
    padding: 10px 20px;
    font-size: 16px;
    border: 1px solid black00;
    background: #EAE1BC;
    color: #212121;
    font-weight: bold;
    display: block;
    font-family: Open Sans;
    -webkit-box-shadow: inset 8px 8px 8px -8px #ccc5a5;
    box-shadow: inset 8px 8px 8px -8px #ccc5a5;
}

.ui-window-content {
    border-color: 1px solid #D9D8D2;
    background-color: #FAF8EF;
    overflow-y: scroll;
}

    .ui-window-content div {
        margin: 10px 20px 10px 20px;
    }

    .ui-window-content span {
        margin: 10px;
    }

.ui-button-link {
    width: 180px;
    background-color: #C5BB9B;
    display: inline-block;
    text-align: center;
    line-height: 3em;
    cursor: pointer;
    border: 1px solid #3D0000;
    -moz-border-radius: 8px;
    -webkit-border-radius: 8px;
    border-radius: 8px;
}

.ui-autocomplete {
    position: absolute;
    cursor: default;
    z-index: 4000 !important;
}

.searchResults, .personnel-listing {
    padding: 0 20px 20px 20px;
    margin: 0 0 20px 0;
    background-color: white;
    min-height: 500px;
}

    .searchResults .summary {
        border-bottom: 1px dotted #565555;
        padding: 10px 0 10px 0;
    }

        .searchResults .summary .results {
            font-family: "Open Sans";
            font-size: 16px;
        }

        .searchResults .summary .resultsFor {
            font-family: Arial;
            font-style: italic;
            font-size: 14px;
            border-left: 1px solid black;
            margin: 0 0 0 10px;
            padding: 0 0 0 10px;
        }

    .searchResults .result {
        padding: 15px 0 15px 0px;
        border-bottom: 1px solid #a58f75;
        position: relative;
        color: #4a4949;
        font-size: 14px;
        line-height: 1.2;
        overflow: auto;
    }

        .searchResults .result .link {
            display: block;
            float: right;
            padding: 5px 15px 5px 15px;
            background-color: #8f0c30;
            color: White;
            font-family: "Open Sans";
            font-size: 11px;
            font-weight: 800;
            border: none;
        }

        .searchResults .result .image {
            position: absolute;
            top: 15px;
            left: 0;
            width: 75px;
            height: 75px;
        }

        .searchResults .result .name {
            font-size: 18px;
            float: left;
            line-height: 22px;
        }

        .searchResults .result .email {
            text-decoration: underline;
            float: left;
        }

        .searchResults .result .title {
            float: left;
            margin-top: 10px;
        }

        .searchResults .result .phone {
            float: left;
            margin-right: 20px;
            margin-top: 10px;
        }

    .searchResults .pagingInfo {
        margin: 10px 0 0 0;
    }

        .searchResults .pagingInfo .pagingNavigation {
            color: #98002E;
        }

.ie7 .searchResults {
    zoom: 1;
}

    .ie7 .searchResults .pagingInfo .pagingNavigation {
        color: #98002E;
        margin-top: -17px;
    }

.oldie .totalResults {
    margin-right: 5px;
}

.searchResults .pagingInfo .pagingNavigation > span:first-child {
    border: none;
}

.searchResults .pagingInfo .pagingNavigation > span {
    padding: 0 4px 0 4px;
    border-left: 1px solid black;
    text-decoration: underline;
    cursor: hand;
    cursor: pointer;
}


/* ==|== media queries ====================================================== */

@media only screen and (min-width: 780px) {

    /*.primaryContent .main{
        width:100%;   
        max-width: 940px;
        margin:0 0 0 50px; 
    }
    
    .primaryContent .main>.leftColumn{
        margin:0 60px 0 0;
    }
    
    .directorySearch{
        padding: 10px 45px 10px 45px;     
    }
    
    
    
    .searchResults .pagingInfo .pagingNavigation{
        float:right;
    }*/
    #directorySearchBox, .searchbox {
        min-width: 85%;
    }
}

@media only screen and (min-width: 1024px) {

    /*.directorySearch>.filters{
        padding:15px 5% 15px 5%;
        margin:10px 0 0 -5%;
        width:100%;
    }*/

}

@media only screen and (min-width: 1085px) {
}

/* Form formatting */
.profile {
    padding: 10px 45px 10px 45px;
    background-color: #f5f5f5;
    color: #313131;
    border: 1px solid #c1c1c1;
}

    .profile div {
        margin: 5px;
    }

    .profile .offset {
        margin-left: 160px;
    }

    .profile label {
        font-family: "Open Sans";
        font-size: 17px;
        color: #4A4949;
        display: inline-block;
        width: 150px;
        text-align: left;
    }
    /*
.profile span {
	font-family: "Open Sans";
	font-size:18px;
	color:#4A4949;
}*/
    .profile input[type=text] {
        color: #4A4949;
        width: 300px;
        -ms-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        vertical-align: middle;
    }

    .profile select {
        line-height: 25px;
        color: #4A4949;
        width: 230px;
        /*width: expression(this.width > 230? 230: true);
	max-width:230px;*/
        vertical-align: middle;
    }

.anchorLinks {
    margin-top: 10px;
}

    .anchorLinks > a {
        margin: 0 5px 0 0;
    }

.selfprofile {
    color: #4A4949;
    font-size: 14px;
}

    .selfprofile div {
        margin: 7px 0;
    }

    .selfprofile .image {
        width: 75px;
        height: 75px;
        display: block;
        margin: 10px auto;
    }

    .selfprofile .name {
        font-size: 18px;
    }

button, a.button {
    display: inline-block;
    padding: 15px 25px;
    font-size: 16px;
    border-radius: 3px;
    background: #98002e;
    color: white;
    cursor: pointer;
    border: none;
    box-shadow: 0px 2px 1px -1px rgba(0,0,0,0.3);
}

    button:hover, button:focus, a.button:hover, a.button:focus {
        outline: none;
        background-color: #740023;
        -webkit-transition: background-color 0.4s;
        transition: background-color 0.4s;
    }

    button:active, a.button:active {
        -webkit-transition: none;
        transition: none;
        background-color: #740023;
    }


table.results {
    font-family: Verdana, Arial, Sans-Serif;
    font-size: 11px;
    border-width: 1px;
    border-collapse: collapse;
    margin-bottom: 20px;
    border-spacing: 10px;
    -webkit-box-shadow: 0px 0px 7px #434343;
    box-shadow: 0px 0px 7px #434343;
}

    table.results th {
        font-size: 16px;
        padding: 8px;
        color: #f7f5f3;
        background-color: #483B2D;
        background: -webkit-linear-gradient(#755F48, #483B2D);
        background: -moz-linear-gradient(#755F48, #483B2D);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#755F48', endColorstr='#483B2D',GradientType=0 );
        border-bottom: 1px solid #30271E;
        border-top: 1px solid #A68B6E;
    }

    table.results td {
        font-size: 16px;
        border-width: 1px;
        padding: 8px;
        color: #444;
        background-color: #EEE;
        border-bottom: 1px solid #E5E2CF;
        vertical-align: middle;
    }

.smallMasthead .masthead:before {
    background-image: none;
}

.smallMasthead .masthead {
    overflow: visible;
    background-image: none;
    background: transparent;
}

    .smallMasthead .masthead > div {
        padding: 0;
        top: -10px;
        max-width: 100%;
    }

.editProfile a {
    float: right;
    background-image: none;
}

.SearchButtonClass {
    position: relative;
    display: inline-block;
    overflow: hidden;
    cursor: pointer;
    float: right;
    padding: 1rem 2rem;
    max-width: 95%;
    margin: 0 auto;
    outline: none;
    background: #fc0;
    color: #000;
    -webkit-border-radius: 6px;
    -moz-border-radius: 6px;
    border-radius: 6px;
    -webkit-border-radius: 0.375rem;
    -moz-border-radius: 0.375rem;
    border-radius: 0.375rem;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    -webkit-transition: all 0.2s;
    transition: all 0.2s;
    text-transform: uppercase;
    font-size: 0.9rem;
    font-weight: 700;
    letter-spacing: 0.06rem;
    min-width: 6rem;
    height: 2.5rem;
    border: none;
    /*padding: 0.25rem 3rem 0.25rem 1rem;*/
    color: #000;
    font-size: 1rem;
    cursor: pointer;
    z-index: 2;
    clear: both;
    margin-bottom: 2rem;
    margin-top: 0px;
    /*position: relative;*/
    /*background-image: url(images/calendar.gif); 
     background-color: transparent; 
    background-repeat: no-repeat;  
    background-position: 0px 0px;*/
}

.ProfileLink {
    position: relative;
    left: 130px;
    top: -142px;
    float: right;
    text-align: right;
    text-wrap: none;
}


.responsiveForm input[type=submit], .responsiveForm a.button {
    display: inline-block;
    padding: 10px 55px;
    font-size: 14px;
    border-radius: 3px;
    background: #98002e;
    color: white;
    cursor: pointer;
    border: none;
    box-shadow: 0px 2px 1px -1px rgba(0,0,0,0.3);
    display: block;
    margin-top: 0px;
    background-image: url(../Content/images/magnifier.png);
    /*background-color:transparent;*/
    background-repeat: no-repeat;
    background-position: 80px 5px;
    background-size: 32px;
    padding-left: 12px;
    margin-right: 5px;
}



.searchResults tr:hover {
    background-color: #f8f8f8;
}


.searchResults h1 {
    font-size: 1rem;
    max-width: 32rem;
    display: inline-block;
    padding: 0 0.5rem;
    margin-bottom: 0.75rem;
    line-height: 0.9;
    margin: 0;
    text-align: left;
    color: #444;
    position: relative;
}

.searchResults .countResults {
    margin-left: 0.5rem;
    font-size: 1rem;
    font-weight: 300;
    color: #999;
}

.searchResults th {
    /*th-header-asc*/
    background: #f8f8f8;
    /*color: #444;*/
    position: relative;
    vertical-align: top;
    text-align: left;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    font-weight: 300;
    color: #999;
    border: none;
    /*width: 22%;*/
    margin: 0;
    padding-top: 1rem;
    /*padding-left: 0.5rem;*/
    /*padding-right: 0.5rem;*/
    padding-bottom: 0.25rem;
    cursor: pointer;
    float: left;
}

.searchResults .person {
    font-weight: bold;
    font-size: 1rem;
    /*font-weight: 500;*/
    line-height: 1.1;
    display: block;
    color: #98002e;
    /*width:33%;*/
}

.searchResults div a {
    text-align: left;
}


.searchResults td {
    vertical-align: top;
    /*width: 100%;*/
    line-height: 1.2;
    border: none;
    border-top: 1px solid #f2f2f2;
    padding: 0.7rem 0.5rem 0.7rem 0rem;
    margin: 0;
    font-size: 0.95rem;
    font-weight: 300;
    color: #444;
    float: left;
}

.searchResults table {
    display: table;
    position: relative;
    /*border-collapse: separate;
    border-spacing: 2px;*/
    border-color: grey;
    /*width: 100%;*/
}

.searchResults .title {
    margin-top: 0.1rem;
    font-size: 0.8rem;
    display: block;
    /*width : 33%;*/
}

.searchResults .department {
    margin-top: 0.1rem;
    font-size: 0.8rem;
    display: block;
    /*width : 33%;*/
    /*padding:5px 5px 4px 4px;
    margin-bottom: 10px;*/
}

.searchResults .email {
    /*display: block;*/
    /*padding-right: 1rem;
    margin: 0 0.8rem 0.2rem 0;*/
    /*color: #000;*/
    white-space: nowrap;
    /*text-align:left;*/
    font-size: 0.85rem;
    font-weight: bold;
    /*width: 33%;*/
}

.searchResults .phone {
    /* display: block;
    padding-right: 1rem;
    margin: 0 0.8rem 0.2rem 0;*/
    /*color: #000;
    white-space: nowrap;*/
    /*text-align:left;*/
    font-size: 0.8rem;
    color: black;
    /*width: 33%;*/
}

.searchResults a {
    border-bottom: none;
}

.highlight {
    /*font-weight: 700;*/
    background-color: yellow;
}

.test a {
    border-bottom: none;
    float: left;
    font-weight: 700;
    position: absolute;
    padding-left: 1.5rem;
    /* margin: -0.7rem 0 0.5rem 0;*/
    font-size: 0.8rem;
    line-height: 1.5rem;
}

.show_hide a {
    /*display:none;*/
    border-bottom: none;
    position: absolute;
    /*  position:relative;
    float:left;*/
    content: '+';
    width: 1.2rem;
    height: 1.2rem;
    /*top: 0;
    left: 0;*/
    /*background: #fc0;
    color: #fff;*/
    background: #98002e;
    color: white;
    text-shadow: 0 1px 0 rgba(0,0,0,0.1);
    text-align: center;
    line-height: 0.9;
    font-size: 1.2rem;
    border-radius: 0.25rem;
}


@media only screen and (max-width: 760px), (max-device-width: 1024px) and (min-device-width: 768px) {
    .searchResults .person .title .department .email .phone {
        position: relative;
        padding-left: 50%;
        display: block;
    }

    .searchResults .person {
        padding-top: 0.5rem;
        border-top: 1px solid #f2f2f2;
    }

    .searchResults td {
        border: none;
        padding: 0.4rem 0rem 0.4rem 0rem;
    }

    .searchResults th {
        display: none;
    }
}
```

**Comment by mandythomas** [comment]
@nicholasnadel Nick this branch probably isn't needed now. Negin Ahmadian modified the custom.css that was used for the Phone Directory and is utilizing the font settings in our master.css now. No other apps on webfarm had the issue, it was isolated to that one as far as we know, and because they overrode the sitewide styles.

**Comment by nicholasnadel** [comment]
> @nicholasnadel Nick this branch probably isn't needed now. Negin Ahmadian modified the custom.css that was used for the Phone Directory and is utilizing the font settings in our master.css now. No other apps on webfarm had the issue, it was isolated to that one as far as we know, and because they overrode the sitewide styles.

Thanks @mandythomas. Closing this PR

**Pull request closed without merging**
