### PR TITLE
Site-Wide h1-h2 title font changes

### PR DESCRIPTION
**Pull request by waidelacruz**
Title font changes to Futura for h1/h2 headers.

### CODE REVIEW

**Comment by tatwell** [comment]
You probably did a global search, but just to confirm, this is what I find when I grep the stylesheets for `h1`. Note: this will list some stylesheet rules without a font-family setting:

```
cascade-assets atwell$ grep -Rni h1 app/assets/stylesheets/
app/assets/stylesheets//base/defaults.scss:375:h1, h2, h3, h4, h5, h6 {
app/assets/stylesheets//base/defaults.scss:383:h1 {
app/assets/stylesheets//layout_old/faculty/primary-content.scss:3:              .main h1 {
app/assets/stylesheets//layout_old/primary-content.scss:80:       h1 {
app/assets/stylesheets//themes/home.scss:5:h1, h2, h3, h4, h5, h6 {
app/assets/stylesheets//widgets/hero/side_panel.scss:196:    h1 {
app/assets/stylesheets//widgets/hero/side_panel.scss:232:    h1, h2, p {
```

For `h2`, it lists 58 different lines among the stylesheets.

If you did catch all settings you wanted to, then 👍 .

**Comment by homeofmatt** [comment]
Assuming you updated every setting you needed to, 👍

**Comment by waidelacruz** [comment]
@tatwell Those h2 you have listed on your grep don’t call for font-family.

**Comment by tatwell** [comment]
Also counted 35 occurrences of `proxima` in stylesheets, FWIW:

```
cascade-assets atwell$ grep -Rni proxima app/assets/stylesheets/ | wc -l
      35
```

**Comment by waidelacruz** [comment]
@tatwell Yep, we're only changing title H1/H2's, not all instances of Proxima Nova.

**Pull request merged**
