### PR TITLE
Degrees and programs post launch enhancements

### PR DESCRIPTION
**Pull request by sharissis-brei**
@tatwell @mandythomas This PR is for all Degrees and Programs enhancements. I've put these changes on dev Cascade for you to review.

### CODE REVIEW

**Comment by mandythomas** [comment]
@Sean-BREI or @sharissis-brei I'm not clear on why one of the changes in dap-feature.json is to populate a field with a value of "Underwater Basket Weaving". If you mean it to be a default shouldn't we do something more intuitive? Also, with 30 files it's hard to get my head around what you're changing in the code and why. I assume once pull request is approved, and we merge it to development branch, we'll set this all up on the DEV-Cascade instance and be able to see more easily how your changes are working and put it up against the list of whatever we'd originally asked you to modify. Is that how we plan to proceed?

**Comment by sharissis-brei** [comment]
Hi @mandythomas, I apologize for the confusion with "Underwater Basket Weaving" – it's a dummy data program name that I forgot to take out. I will remove it.

The reason you are seeing some many files changed this time around is because there were some markup changes to accommodate the UI alterations we made, as opposed to just JS changes. There are a number of partials that make up the page's markup, and many of them changed at least slightly. That, combined with fact that many of the changed files are the files generated to build, is what's causing the higher number of files changed. If you have questions about any specific files, please let me know.

As for what's been changed, it would be easiest to view the changes commit by commit. I've tried to make each commit message as descriptive as possible, but if you'd like to me delve into the details of anything specific, I'd be happy to explain.

These changes are already on DEV-Cascade for you to view.

**Comment by sharissis-brei** [comment]
@mandythomas, you'll notice the file change count went up. This is because I've swapped out the list icon SVG, and while doing so, updated Icomoon in the project.

**Comment by mandythomas** [comment]
@tatwell Did you want to look this over before we merge to Development? It's Sarah's mods for the new Degrees & Programs section. I see you reviewed but there wasn't an Approve. Wasn't sure if you wanted to do that or not.

**Comment by tatwell** [comment]
@mandythomas I approved the pull-request. In the future, I'd prefer to see formats like `formats/Degrees-programs/PrimaryContent.vm` follow our new Velocity guide:

- https://wimops.chapman.edu/wiki/Velocity

But development of this project predated the guide.

**Pull request merged**
