### PR TITLE
Update 3 col priority of primary/right/left on mobile view

### PR DESCRIPTION
**Pull request by nicholasnadel**
story: https://trello.com/c/YKuuU27o
demo: https://dev-www.chapman.edu/test-section/nick-test/3col-moble-priority.aspx

### CODE REVIEW

**Comment by mandythomas** [comment]
@nicholasnadel Yesterday I did a pull request (and merge) into Development that included some files which are now showing up in this pull request. My first question is why. Did you do your compare to Development a while back before I'd done those, or today? For the most part it’s showing the same changes I made in various files, however in defaults.scss I don’t see the new “table caption” styles I had added yesterday. They were on line 339 in the file that is now in Development branch but they aren’t showing in this pull request. If I’m reading it right, seems like my change will be missing when you merge.

**Comment by mandythomas** [comment]
@cbryant24 Aren't there more files that need to be part of this pull request? Did you change the templates to add the new classes to some DIVs, or do you do that in velocity format(s) or done at pageload thru some javascript functions? All I see in this pull request is the CSS classes defined

**Comment by cbryant24** [comment]
@mandythomas I'm not sure what you mean. Are you referring to this (pull request)[https://github.com/chapmanu/cascade-assets/pull/509] if so I think that request is connected to this request

**Comment by nicholasnadel** [comment]
> All I see in this pull request is the CSS classes defi

@mandythomas @cbryant24 This was my story -- it's all handled via CSS

**Pull request merged**
